<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE suite SYSTEM "https://testng.org/testng-1.0.dtd">
<suite thread-count="1" name="Failed suite [Surefire suite]" verbose="0">
  <test thread-count="1" name="Surefire test(failed)" verbose="0">
    <classes>
      <class name="haniehsadatiacademy.SeleniumFrameDesign.SubmitOrderTestCase">
        <methods>
          <include name="launchApplication"/>
          <include name="tearDown"/>
          <include name="SubmitOrder"/>
          <include name="OrderHistoryTest"/>
        </methods>
      </class> <!-- haniehsadatiacademy.SeleniumFrameDesign.SubmitOrderTestCase -->
      <class name="runner.TestNGTestRunner">
        <methods>
          <include name="setUpClass"/>
          <include name="runScenario" invocation-numbers="0"/>
          <include name="tearDownClass"/>
        </methods>
      </class> <!-- runner.TestNGTestRunner -->
      <class name="haniehsadatiacademy.SeleniumFrameDesign.ErrorValidationsTest">
        <methods>
          <include name="launchApplication"/>
          <include name="LoginErrorValidation"/>
          <include name="tearDown"/>
          <include name="ProductErrorValidation"/>
        </methods>
      </class> <!-- haniehsadatiacademy.SeleniumFrameDesign.ErrorValidationsTest -->
    </classes>
  </test> <!-- Surefire test(failed) -->
</suite> <!-- Failed suite [Surefire suite] -->
